<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Next</name>
   <tag></tag>
   <elementGuidId>f88a40b5-d165-418e-acea-b856b0dc6ecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.carousel-control-next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='carouselExampleIndicators']/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>02b2605a-03ea-40c5-b6a4-eb086baf48d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carousel-control-next</value>
      <webElementGuid>5f534bdb-e94a-4471-b8b9-13fcd1bc88bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#carouselExampleIndicators</value>
      <webElementGuid>df357767-d01f-4d3e-87f9-41f61c45e2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d35f2044-74dd-4475-8dae-8f86c1aaf3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slide</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>eecc8121-0bcc-4cfc-a412-d498917e1ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          
          Next
        </value>
      <webElementGuid>f3c0f41f-983b-4e1e-b809-cde62c6f96bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carouselExampleIndicators&quot;)/a[@class=&quot;carousel-control-next&quot;]</value>
      <webElementGuid>df7c8d53-89e4-4595-99a9-61ec72445b0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carouselExampleIndicators']/a[2]</value>
      <webElementGuid>1d4c92b1-dddb-481b-af5b-7db7e621e869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::a[1]</value>
      <webElementGuid>d919e74c-15f0-4db9-88df-e1e4266c9cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[1]/following::a[6]</value>
      <webElementGuid>9a9d411c-dfae-4bc0-ae5a-39fab2c6b2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATEGORIES'])[1]/preceding::a[1]</value>
      <webElementGuid>e4f3b576-7f79-4f17-b901-2510462e8b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#carouselExampleIndicators')])[2]</value>
      <webElementGuid>4cdbfe96-9d31-4540-99f9-0dd759ee23ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>f76e0fde-6411-4174-b54e-012300931212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#carouselExampleIndicators' and (text() = '
          
          Next
        ' or . = '
          
          Next
        ')]</value>
      <webElementGuid>a94c39ae-2cae-4af4-992b-090fc7bdeba5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
